import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { CommandDemo } from "@/components/command";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className} relative h-screen w-full flex-col justify-between`}
      >
        <div className="flex h-full w-full flex-col">
          <Header />
          {children}
          <CommandDemo />
        </div>
        <Footer />
      </body>
    </html>
  );
}
