openapi: "3.0.2"
info:
  title: 고급웹프로그래밍 프로젝트
  version: "1"
servers:
  - url: https://localhost:3300/v1
paths:
  /test:
    get:
      responses:
        "200":
          description: OK

  /course/findOne:
    $ref: "./course/index.yml#/paths/~1findOne"

  /course/search:
    $ref: "./course/index.yml#/paths/~1search"



components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
          description: UUID 형식의 사용자 ID
        name:
          type: string
          description: 사용자 이름

