openapi: "3.0.2"
info:
  title: type 정의
  version: "1"

paths:
  /type:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/type"

components:
  schemas:
    type:
      type: object
      properties:
        langMode:
          $ref: "#/components/schemas/langMode"
        title:
          type: string
          description: 제목
        code:
          type: string
          description: 과목 코드
        openDepartment:
          type: string
          description: 개설학과

    langMode:
      type: string
      enum:
        - ko
        - en
      description: 언어 모드. 한국어 또는 영어 중 하나로 지정되어야 합니다.

    geoLocation:
      type: object
      properties:
        latitude:
          type: number
          format: double
          description: 위도
        longitude:
          type: number
          format: double
          description: 경도

